---
title: "HW6_Okonkwo_co2554"
author: "Camille Okonkwo"
date: "2024-03-20"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Prepare the data
```{r}
hwdata2 = read.csv("data/hwdata2.csv")

hwdata2.1 = uncount(hwdata2, weights = count)

# re-factor variables
hwdata2.1$pared2 = relevel(as.factor(hwdata2.1$pared),
                            ref="0")

hwdata2.1$public2 = relevel(as.factor(hwdata2.1$public),
                            ref="0")

hwdata2.1$apply = as.factor(hwdata2.1$apply)
                  
table(hwdata2.1$apply)
```

# Fit the ordinal logistic model
```{r}
library(VGAM)

# proportional odds model
fit = vglm(apply ~ pared2 + public2,
           data = hwdata2.1,
           family = cumulative("logitlink",
                               parallel = TRUE))

summary(fit)
```

# Test the proportional odds assumption
```{r}
# non- proportional odds model
fit2 = vglm(apply ~  pared2 + public2,
            data = hwdata2.1,
           family = cumulative("logitlink",
                               parallel = FALSE))

summary(fit2)

lrtest(fit2, fit)
```

# Calcualte odds ratio & 95% CI of a lower rating
```{r}
exp(cbind(OR = coef(fit), confint(fit)))
```

# Estimate the probability of rating “very likely” 
```{r}
# predicted probabilities
newdata = data.frame(pared2=c("0","1"),
                     public2=c("1", "0"))
pred = predict(fit, newdata=newdata, "response")
cbind(newdata,pred)
```

# Fit a multinomial logistic regression model to the data using “unlikely” as the reference category.
```{r}
fit3 = vglm(apply ~  pared2 + public2,
            data = hwdata2.1,
           family = multinomial(refLevel = "1"))

summary(fit3)

# odds ratio and 95% CI
exp(cbind(OR=coef(fit3),confint(fit3)))

# predicted probabilities
d_hwdata2.1 = data.frame(pared2=rep(c("0","1"),2),
                         public2=rep(c("1","0"),2))
                     
pred2 = predict(fit3, newdata=d_hwdata2.1, "response")

cbind(d_hwdata2.1,pred2)
```

